# Generated by Django 4.2.2 on 2023-07-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contacto_delete_consulta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nuevo',
            new_name='congelado',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tipo_consulta',
            field=models.IntegerField(choices=[[0, 'Consulta'], [1, 'Reclamo'], [2, 'Sugerencia'], [3, 'Felicitaciones']]),
        ),
    ]
